// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import PollController from "./poll_controller";
import FormReloadingController from "./form_reloading_controller";
application.register("poll", PollController);
application.register("form_reloading", FormReloadingController);
