inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "lib/refinery/**/*"
    - "lib/liquid/**/*"
    - "tmp/**/*"
    - "features/**/*"
    - "bin/*"
  DisplayStyleGuide: true
  DisplayCopNames: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Performance/OpenStruct:
  Exclude:
    - "spec/**/*"
