inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.2
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/refinery/**/*'
    - 'lib/liquid/**/*'
    - 'tmp/**/*'
    - 'features/**/*'
  DisplayStyleGuide: true
  DisplayCopNames: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false