sudo: required

language: ruby

dist: bionic

rvm:
  - 2.3.8

services:
  - mongodb
  - xvfb

before_script:
  - cp config/application.yml.example config/application.yml
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache: bundler

bundler_args: --without production

jobs:
  include:

    - stage: test
      name: 'Rspec'
      script:
        - bundle exec rspec

    - stage: test
      name: 'Rubocop'
      script:
        - bundle exec rubocop

    - stage: test
      name: 'bundle audit'
      script:
        - gem install bundler-audit
        - bundle audit update
        - bundle audit check

    - stage: test
      name: 'brakeman check'
      script:
        - gem install brakeman
        - brakeman --run-all-checks

  allow_failures:

    - stage: test
      name: 'Rubocop'
      script:
        - bundle exec rubocop

    - stage: test
      name: 'bundle audit'
      script:
        - gem install bundler-audit
        - bundle audit update
        - bundle audit check

    - stage: test
      name: 'brakeman check'
      script:
        - gem install brakeman
        - brakeman --run-all-checks
