sudo: required
language: ruby
rvm:
  - 2.3.1
services:
  - mongodb
before_script:
  - cp config/application.yml.example config/application.yml
  - sh -e /etc/init.d/xvfb start
script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache: bundler
bundler_args: --without production
