language: ruby

rvm:
  - 2.6.5

services:
  - mongodb
  - xvfb

addons:
  chrome: stable

cache: bundler

before_script:
  - cp config/application.yml.example config/application.yml
  - gem install bundler --version $(tail -n1 Gemfile.lock)
  - RAILS_ENV=test bin/rails db:create --trace
  - RAILS_ENV=test bin/rails db:migrate --trace

jobs:
  include:

    - stage: test
      name: 'Rspec'
      script:
        - bundle exec rspec

    - stage: test
      name: 'Rubocop'
      script:
        - bundle exec rubocop

    - stage: test
      name: 'bundle audit'
      script:
        - gem install bundler-audit
        - bundle audit update
        - bundle audit check

    - stage: test
      name: 'brakeman check'
      script:
        - gem install brakeman
        - brakeman --run-all-checks

  allow_failures:

    - stage: test
      name: 'Rubocop'
      script:
        - bundle exec rubocop

    - stage: test
      name: 'bundle audit'
      script:
        - gem install bundler-audit
        - bundle audit update
        - bundle audit check

    - stage: test
      name: 'brakeman check'
      script:
        - gem install brakeman
        - brakeman --run-all-checks
